[package]
name = "checksec"
version = "0.1.0"
authors = ["3akur6 <464074069@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.3.4"
colored = "2.0.0"
clap = "2.33.3"
